# Generated by Django 3.2.6 on 2021-08-28 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210828_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='type',
            new_name='type',
        ),
    ]
