# Generated by Django 3.2.6 on 2021-09-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_watchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='bid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
