# Generated by Django 3.2.6 on 2021-09-15 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='creator',
        ),
        migrations.AddField(
            model_name='listing',
            name='creators',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, related_name='creators', to='auctions.user'),
            preserve_default=False,
        ),
    ]
