# Generated by Django 3.2.6 on 2021-09-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listing_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_status',
            field=models.BooleanField(default=True),
        ),
    ]
