# Generated by Django 3.2.6 on 2021-09-16 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bidder',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, related_name='bidder', to='auctions.user'),
            preserve_default=False,
        ),
    ]
