# Generated by Django 3.2.6 on 2021-09-17 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_comment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='watcher',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, related_name='watcher', to='auctions.user'),
            preserve_default=False,
        ),
    ]
