# Generated by Django 3.2.6 on 2021-09-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_listing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default='No Category Listed', max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='link',
            field=models.CharField(default='https://cdn-icons-png.flaticon.com/512/3125/3125669.png', max_length=128),
        ),
    ]
